import { getCurrentMockUser } from "../../../services/auth/mockUser";
import { cicloRoleLabels } from "./ciclo.permissions";
import type {
  CicloCatalogs,
  CicloMedicion,
  CicloRole,
  CurrentUser,
  CursoSintesis,
  Facultad,
  PlanEstudio,
  ProgramaAcademico,
  Seccional,
} from "./ciclo.types";

export const DEFAULT_CICLO_ROLE: CicloRole = "director";

export const seccionales: Seccional[] = [
  { id: "cali", nombre: "Seccional Cali" },
  { id: "bogota", nombre: "Sede Bogotá" },
  { id: "medellin", nombre: "Seccional Medellín" },
  { id: "cartagena", nombre: "Seccional Cartagena" },
];

export const facultades: Facultad[] = [
  { id: "ing-cali", nombre: "Facultad de Ingeniería", seccionalId: "cali" },
  { id: "artes-cali", nombre: "Facultad de Artes y Diseño", seccionalId: "cali" },
  { id: "ing-bog", nombre: "Facultad de Ingeniería", seccionalId: "bogota" },
  { id: "salud-bog", nombre: "Facultad de Salud", seccionalId: "bogota" },
  { id: "ing-med", nombre: "Facultad de Ingeniería", seccionalId: "medellin" },
  { id: "ing-cart", nombre: "Facultad de Ingeniería", seccionalId: "cartagena" },
];

export const programas: ProgramaAcademico[] = [
  {
    id: "sis-cali",
    nombre: "Ingeniería de Sistemas",
    facultadId: "ing-cali",
    seccionalId: "cali",
    estado: "activo",
  },
  {
    id: "ind-cali",
    nombre: "Ingeniería Industrial",
    facultadId: "ing-cali",
    seccionalId: "cali",
    estado: "activo",
  },
  {
    id: "danza-cali",
    nombre: "Licenciatura en Danza y Performance",
    facultadId: "artes-cali",
    seccionalId: "cali",
    estado: "inactivo",
  },
  {
    id: "sis-bog",
    nombre: "Ingeniería de Sistemas",
    facultadId: "ing-bog",
    seccionalId: "bogota",
    estado: "activo",
  },
  {
    id: "multimedia-bog",
    nombre: "Ingeniería Multimedia",
    facultadId: "ing-bog",
    seccionalId: "bogota",
    estado: "activo",
  },
  {
    id: "biomedica-bog",
    nombre: "Ingeniería Biomédica",
    facultadId: "salud-bog",
    seccionalId: "bogota",
    estado: "inactivo",
  },
  {
    id: "agro-med",
    nombre: "Ingeniería Agroindustrial",
    facultadId: "ing-med",
    seccionalId: "medellin",
    estado: "activo",
  },
  {
    id: "sis-cart",
    nombre: "Ingeniería de Sistemas",
    facultadId: "ing-cart",
    seccionalId: "cartagena",
    estado: "activo",
  },
];

export const planes: PlanEstudio[] = [
  { id: "sis-cali-2024-2", nombre: "Plan 2024-2", programaId: "sis-cali", estado: "activo" },
  { id: "sis-cali-2024-1", nombre: "Plan 2024-1", programaId: "sis-cali", estado: "activo" },
  { id: "ind-cali-2024-2", nombre: "Plan 2024-2", programaId: "ind-cali", estado: "activo" },
  { id: "danza-cali-2024-1", nombre: "Plan 2024-1", programaId: "danza-cali", estado: "inactivo" },
  { id: "sis-bog-2024-2", nombre: "Plan 2024-2", programaId: "sis-bog", estado: "activo" },
  { id: "sis-bog-2015-1", nombre: "Plan 2015-1", programaId: "sis-bog", estado: "inactivo" },
  { id: "multimedia-bog-2024-2", nombre: "Plan 2024-2", programaId: "multimedia-bog", estado: "activo" },
  { id: "biomedica-bog-2015-1", nombre: "Plan 2015-1", programaId: "biomedica-bog", estado: "inactivo" },
  { id: "agro-med-2024-2", nombre: "Plan 2024-2", programaId: "agro-med", estado: "activo" },
  { id: "sis-cart-2024-2", nombre: "Plan 2024-2", programaId: "sis-cart", estado: "activo" },
];

export const cursosSintesis: CursoSintesis[] = [
  {
    id: "cur-sis-cali-701",
    nombre: "Proyector Integrador I",
    codigo: "SIS-701",
    creditos: 3,
    semestre: 7,
    nucleo: "Síntesis",
    programaId: "sis-cali",
    planId: "sis-cali-2024-2",
    docente: "Antonio Rodríguez",
    tipoVinculacion: "Cátedra",
    competenciasAsignadas: 3,
    nivelCompromiso: "A",
    asignadoANucleoSintesis: true,
  },
  {
    id: "cur-sis-cali-702",
    nombre: "Proyector Integrador II",
    codigo: "SIS-702",
    creditos: 3,
    semestre: 8,
    nucleo: "Síntesis",
    programaId: "sis-cali",
    planId: "sis-cali-2024-2",
    docente: "Camilo Castro",
    tipoVinculacion: "Tiempo completo",
    competenciasAsignadas: 0,
    nivelCompromiso: "A",
    asignadoANucleoSintesis: true,
  },
  {
    id: "cur-sis-cali-703",
    nombre: "Trabajo de Grado",
    codigo: "SIS-703",
    creditos: 4,
    semestre: 10,
    nucleo: "Síntesis",
    programaId: "sis-cali",
    planId: "sis-cali-2024-2",
    docente: "Nelly Torres",
    tipoVinculacion: "Medio tiempo",
    competenciasAsignadas: 4,
    nivelCompromiso: "A",
    asignadoANucleoSintesis: true,
  },
  {
    id: "cur-sis-cali-704",
    nombre: "Práctica Profesional",
    codigo: "SIS-704",
    creditos: 6,
    semestre: 9,
    nucleo: "Síntesis",
    programaId: "sis-cali",
    planId: "sis-cali-2024-2",
    docente: "Juliana Mejía",
    tipoVinculacion: "Medio tiempo",
    competenciasAsignadas: 2,
    nivelCompromiso: "",
    asignadoANucleoSintesis: true,
  },
  {
    id: "cur-sis-cali-705",
    nombre: "Seminario de Investigación",
    codigo: "SIS-705",
    creditos: 2,
    semestre: 9,
    nucleo: "Síntesis",
    programaId: "sis-cali",
    planId: "sis-cali-2024-2",
    docente: "Santiago Fonseca",
    tipoVinculacion: "Medio tiempo",
    competenciasAsignadas: 2,
    nivelCompromiso: "R",
    asignadoANucleoSintesis: false,
  },
  {
    id: "cur-sis-cali-801",
    nombre: "Proyecto Integrador Avanzado",
    codigo: "SIS-801",
    creditos: 3,
    semestre: 8,
    nucleo: "Síntesis",
    programaId: "sis-cali",
    planId: "sis-cali-2024-1",
    docente: "Laura Ramírez",
    tipoVinculacion: "Tiempo completo",
    competenciasAsignadas: 3,
    nivelCompromiso: "A",
    asignadoANucleoSintesis: true,
  },
  {
    id: "cur-ind-cali-701",
    nombre: "Proyecto de Optimización Industrial",
    codigo: "IND-701",
    creditos: 3,
    semestre: 7,
    nucleo: "Síntesis",
    programaId: "ind-cali",
    planId: "ind-cali-2024-2",
    docente: "Marcela Ruiz",
    tipoVinculacion: "Tiempo completo",
    competenciasAsignadas: 3,
    nivelCompromiso: "A",
    asignadoANucleoSintesis: true,
  },
  {
    id: "cur-sis-bog-701",
    nombre: "Proyecto Integrador de Software",
    codigo: "SIS-701",
    creditos: 3,
    semestre: 7,
    nucleo: "Síntesis",
    programaId: "sis-bog",
    planId: "sis-bog-2024-2",
    docente: "Antonio Rodríguez",
    tipoVinculacion: "Tiempo completo",
    competenciasAsignadas: 3,
    nivelCompromiso: "A",
    asignadoANucleoSintesis: true,
  },
  {
    id: "cur-sis-bog-703",
    nombre: "Trabajo de Grado",
    codigo: "SIS-703",
    creditos: 4,
    semestre: 10,
    nucleo: "Síntesis",
    programaId: "sis-bog",
    planId: "sis-bog-2024-2",
    docente: "Nelly Torres",
    tipoVinculacion: "Tiempo completo",
    competenciasAsignadas: 4,
    nivelCompromiso: "A",
    asignadoANucleoSintesis: true,
  },
  {
    id: "cur-mul-bog-801",
    nombre: "Proyecto Transmedia",
    codigo: "MUL-801",
    creditos: 3,
    semestre: 8,
    nucleo: "Síntesis",
    programaId: "multimedia-bog",
    planId: "multimedia-bog-2024-2",
    docente: "Paula Ríos",
    tipoVinculacion: "Cátedra",
    competenciasAsignadas: 3,
    nivelCompromiso: "A",
    asignadoANucleoSintesis: true,
  },
  {
    id: "cur-agro-med-701",
    nombre: "Proyecto Agroindustrial Aplicado",
    codigo: "AGR-701",
    creditos: 3,
    semestre: 7,
    nucleo: "Síntesis",
    programaId: "agro-med",
    planId: "agro-med-2024-2",
    docente: "Diana Cardona",
    tipoVinculacion: "Tiempo completo",
    competenciasAsignadas: 2,
    nivelCompromiso: "A",
    asignadoANucleoSintesis: true,
  },
  {
    id: "cur-sis-cart-701",
    nombre: "Proyecto Integrador Regional",
    codigo: "SIS-701",
    creditos: 3,
    semestre: 7,
    nucleo: "Síntesis",
    programaId: "sis-cart",
    planId: "sis-cart-2024-2",
    docente: "Hernando Díaz",
    tipoVinculacion: "Tiempo completo",
    competenciasAsignadas: 3,
    nivelCompromiso: "A",
    asignadoANucleoSintesis: true,
  },
];

export const mockCiclos: CicloMedicion[] = [];

const mockUsers: Record<CicloRole, CurrentUser> = {
  admin: {
    id: "usr-admin-001",
    nombre: "Juliana Mejía",
    cargo: cicloRoleLabels.admin,
    role: "admin",
    scope: {},
  },
  vice: {
    id: "usr-vice-001",
    nombre: "Ana María Restrepo",
    cargo: cicloRoleLabels.vice,
    role: "vice",
    scope: { seccionalId: "bogota" },
  },
  decano: {
    id: "usr-decano-001",
    nombre: "Carlos Medina",
    cargo: cicloRoleLabels.decano,
    role: "decano",
    scope: { seccionalId: "bogota", facultadId: "ing-bog" },
  },
  director: {
    id: "usr-director-001",
    nombre: "Laura Gómez",
    cargo: cicloRoleLabels.director,
    role: "director",
    scope: { seccionalId: "cali", facultadId: "ing-cali", programaId: "sis-cali" },
  },
  docente: {
    id: "usr-docente-001",
    nombre: "Santiago Torres",
    cargo: cicloRoleLabels.docente,
    role: "docente",
    scope: { seccionalId: "cali", facultadId: "ing-cali", programaId: "sis-cali" },
  },
};

export function normalizeCicloRole(rawRole: string | null | undefined): CicloRole {
  const normalized = String(rawRole ?? "").trim().toLowerCase();

  const aliases: Record<string, CicloRole> = {
    admin: "admin",
    administrador: "admin",
    superadmin: "admin",
    vice: "vice",
    vicerrector: "vice",
    vicerrectoria: "vice",
    vicerrectoría: "vice",
    decano: "decano",
    director: "director",
    directorprograma: "director",
    director_de_programa: "director",
    docente: "docente",
  };

  return aliases[normalized] ?? DEFAULT_CICLO_ROLE;
}

export function getCurrentCicloUser(): CurrentUser {
  const demoUser = getCurrentMockUser();
  const fallbackUser = mockUsers[demoUser.role as keyof typeof mockUsers] ?? mockUsers.admin;

  return {
    ...fallbackUser,
    id: demoUser.id,
    nombre: demoUser.nombre,
    email: demoUser.email,
    cargo: demoUser.cargo || fallbackUser.cargo,
    role: demoUser.role as CurrentUser["role"],
    scope: {
      ...fallbackUser.scope,
      ...demoUser.scope,
    },
  };
}

export function getCicloCatalogs(): CicloCatalogs {
  return {
    seccionales,
    facultades,
    programas,
    planes,
    cursos: cursosSintesis,
  };
}
